# Created by trellis-cli v0.7.1
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  flexyourrights.org:
    site_hosts:
    - canonical: flexyourrights.test
      redirects:
      - www.flexyourrights.test
    local_path: ../site
    admin_email: admin@flexyourrights.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
