# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  flexyourrights.org:
    site_hosts:
      - canonical: www.flexyourrights.org
        redirects:
          - flexyourrights.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:stevesilverman/flexyourrights.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: manual
      cert: ~/ssl/star_flexyourrights_org.crt
      key: ~/ssl/star_flexyourrights_org.key
      # provider: letsencrypt
    cache:
      enabled: true
