# Created by trellis-cli v0.7.1
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  flexyourrights.org:
    site_hosts:
    - canonical: flexyourrights.org
      redirects:
      - www.flexyourrights.org
    local_path: ../site
    branch: master
    repo: git@github.com:stevesilverman/flexyourrights.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
