# Created by trellis-cli v0.7.1
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  flexyourrights.org:
    site_hosts:
    - canonical: fyr2020.k-thx.com
    local_path: ../site
    branch: staging
    repo: git@github.com:stevesilverman/flexyourrights.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
    htpasswd:
      - name: fyr
        password: 2020
